### PR TITLE
Visibility of Nsxt new buttons

### PR DESCRIPTION
**Pull request by gubbe505**
* Changed the visibility of the New button only when a NSX-T providers is available for the user
* Changed the visibility of the Update and Delete button only when the record is part of the NSX-T Network Manager
* Some textual changes

Should help with:
https://github.com/ManageIQ/manageiq-ui-classic/issues/7465

### CODE REVIEW

**Comment by h-kataria** [comment]
@gubbe505 i am running into an error when trying to go to Security Groups or Security Policy list view screen
```
[----] I, [2020-11-02T11:57:07.524020 #30050:4456e5c]  INFO -- :   Rendered /home/hkataria/dev/manageiq-ui-classic/app/views/layouts/_center_div_with_listnav.html.haml (573.3ms)
[----] I, [2020-11-02T11:57:07.524158 #30050:4456e5c]  INFO -- :   Rendered /home/hkataria/dev/manageiq-ui-classic/app/views/layouts/_content.html.haml (597.3ms)
[----] F, [2020-11-02T11:57:07.524347 #30050:4456e5c] FATAL -- : Error caught: [ActionView::Template::Error] uninitialized constant ApplicationHelper::Button::AnyNsxtProvider
/home/hkataria/dev/manageiq-providers-nsxt/app/helper/manageiq/providers/nsxt/toolbar_overrides/security_policies_center.rb:29:in `<class:SecurityPoliciesCenter>'
/home/hkataria/dev/manageiq-providers-nsxt/app/helper/manageiq/providers/nsxt/toolbar_overrides/security_policies_center.rb:5:in `<module:ToolbarOverrides>'
/home/hkataria/dev/manageiq-providers-nsxt/app/helper/manageiq/providers/nsxt/toolbar_overrides/security_policies_center.rb:4:in `<module:Nsxt>'
/home/hkataria/dev/manageiq-providers-nsxt/app/helper/manageiq/providers/nsxt/toolbar_overrides/security_policies_center.rb:3:in `<module:Providers>'
/home/hkataria/dev/manageiq-providers-nsxt/app/helper/manageiq/providers/nsxt/toolbar_overrides/security_policies_center.rb:2:in `<module:ManageIQ>'
/home/hkataria/dev/manageiq-providers-nsxt/app/helper/manageiq/providers/nsxt/toolbar_overrides/security_policies_center.rb:1:in `<top (required)>'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/dependencies/interlock.rb:13:in `loading'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:285:in `const_get'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:285:in `block in constantize'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:281:in `each'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:281:in `inject'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:281:in `constantize'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:326:in `safe_constantize'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/core_ext/string/inflections.rb:79:in `safe_constantize'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper/toolbar/basic.rb:37:in `block in load_extension_classes'
/home/hkataria/dev/manageiq/lib/vmdb/plugins.rb:23:in `each'
/home/hkataria/dev/manageiq/lib/vmdb/plugins.rb:23:in `each'
/home/hkataria/dev/manageiq/lib/vmdb/plugins.rb:11:in `collect'
/home/hkataria/dev/manageiq/lib/vmdb/plugins.rb:11:in `method_missing'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper/toolbar/basic.rb:35:in `load_extension_classes'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper/toolbar/basic.rb:11:in `extension_classes'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper/toolbar/basic.rb:24:in `extension_classes_filtered'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper/toolbar/basic.rb:3:in `definition'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper/toolbar_builder.rb:440:in `build_toolbar_from_class'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper/toolbar_builder.rb:16:in `build_toolbar'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper.rb:442:in `build_toolbar'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/toolbar_helper.rb:7:in `block in toolbar_from_hash'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/toolbar_helper.rb:6:in `each'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/toolbar_helper.rb:6:in `collect'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/toolbar_helper.rb:6:in `toolbar_from_hash'
/home/hkataria/dev/manageiq-ui-classic/app/views/layouts/_center_div_with_listnav.html.haml:9:in `__home_hkataria_dev_manageiq_ui_classic_app_views_layouts__center_div_with_listnav_html_haml___3803791505971524134_70151166235880'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/actionview-5.2.4.4/lib/action_view/template.rb:159:in `block in render'
```

**Comment by gubbe505** [comment]
@h-kataria Fixed renaming AnyNsxtProvider into AnyNsxtNetworkManager. Sorry about that.... :(

**Comment by h-kataria** [comment]
@gubbe505 getting an error when i tried to go to details screen on non-nsxt Security Group
```
[----] F, [2020-11-02T13:14:37.811436 #13975:405c978] FATAL -- : Error caught: [ActionView::Template::Error] uninitialized constant ApplicationHelper::Button::BelongsToAnyNsxtNetworkManager
/home/hkataria/dev/manageiq-providers-nsxt/app/helper/manageiq/providers/nsxt/toolbar_overrides/security_group_center.rb:29:in `<class:SecurityGroupCenter>'
/home/hkataria/dev/manageiq-providers-nsxt/app/helper/manageiq/providers/nsxt/toolbar_overrides/security_group_center.rb:5:in `<module:ToolbarOverrides>'
/home/hkataria/dev/manageiq-providers-nsxt/app/helper/manageiq/providers/nsxt/toolbar_overrides/security_group_center.rb:4:in `<module:Nsxt>'
/home/hkataria/dev/manageiq-providers-nsxt/app/helper/manageiq/providers/nsxt/toolbar_overrides/security_group_center.rb:3:in `<module:Providers>'
/home/hkataria/dev/manageiq-providers-nsxt/app/helper/manageiq/providers/nsxt/toolbar_overrides/security_group_center.rb:2:in `<module:ManageIQ>'
/home/hkataria/dev/manageiq-providers-nsxt/app/helper/manageiq/providers/nsxt/toolbar_overrides/security_group_center.rb:1:in `<top (required)>'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/dependencies/interlock.rb:13:in `loading'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:285:in `const_get'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:285:in `block in constantize'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:281:in `each'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:281:in `inject'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:281:in `constantize'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:326:in `safe_constantize'
/home/hkataria/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.4/lib/active_support/core_ext/string/inflections.rb:79:in `safe_constantize'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper/toolbar/basic.rb:37:in `block in load_extension_classes'
/home/hkataria/dev/manageiq/lib/vmdb/plugins.rb:23:in `each'
/home/hkataria/dev/manageiq/lib/vmdb/plugins.rb:23:in `each'
/home/hkataria/dev/manageiq/lib/vmdb/plugins.rb:11:in `collect'
/home/hkataria/dev/manageiq/lib/vmdb/plugins.rb:11:in `method_missing'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper/toolbar/basic.rb:35:in `load_extension_classes'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper/toolbar/basic.rb:11:in `extension_classes'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper/toolbar/basic.rb:24:in `extension_classes_filtered'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper/toolbar/basic.rb:3:in `definition'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper/toolbar_builder.rb:440:in `build_toolbar_from_class'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper/toolbar_builder.rb:16:in `build_toolbar'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/application_helper.rb:442:in `build_toolbar'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/toolbar_helper.rb:7:in `block in toolbar_from_hash'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/toolbar_helper.rb:6:in `each'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/toolbar_helper.rb:6:in `collect'
/home/hkataria/dev/manageiq-ui-classic/app/helpers/toolbar_helper.rb:6:in `toolbar_from_hash'
/home/hkataria/dev/manageiq-ui-classic/app/views/layouts/_center_div_no_listnav.html.haml:9:in `__home_hkataria_dev_manageiq_ui_classic_app_views_layouts__center_div_no_listnav_html_haml___1881026614476825611_70220258367680'

```

**Comment by gubbe505** [comment]
@h-kataria Grmbl.... last minute renames on Friday when you're in hurry... Shouldn't have done it... Please try again.

**Review by h-kataria — APPROVED** [review]

**Comment by h-kataria** [comment]
@Fryguy @agrare verified changes in UI, looks good.

**Comment by agrare** [comment]
Thanks @gubbe505 !

**Comment by simaishi** [comment]
Kasparov backport details:

```
$ git log -1
commit cc0a50ecb329e5021fcf83bf01ba1fc74a502ce8
Author: Adam Grare <agrare@redhat.com>
Date:   Tue Nov 3 09:39:32 2020 -0500

    Merge pull request #26 from gubbe505/VisibliltyOfNsxtNewButtons

    Visibility of Nsxt new buttons

    (cherry picked from commit eabc173d740b0ccf24d21343e4af9846af8ad69d)
```

**Pull request merged**
